#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

PROG="/usr/bin/CSIdump"

start_instance() {
    local cfg="$1"
    local enabled interface interval port

    config_get_bool enabled "$cfg" enabled 0
    [ "$enabled" -eq 1 ] || return 0

    config_get interface "$cfg" interface
    config_get interval "$cfg" interval "1"
    config_get port "$cfg" port "59876"

    [ -n "$interface" ] || return 0

    procd_open_instance "$cfg"
    procd_set_param command "$PROG" "$interface" "$interval" "$port"
    procd_set_param respawn 5 30 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

start_service() {
    config_load csidump
    config_foreach start_instance csidump
}

service_triggers() {
    procd_add_reload_trigger "csidump"
}
